{
    ZONE_NAME: "REDACTED",
    MONITORING_GRAFANA_OKTA_CLIENT_ID: "REDACTED",
    MONITORING_GRAFANA_OKTA_CLIENT_SECRET: "REDACTED",
    MONITORING_GRAFANA_OKTA_AUTHORIZE: "REDACTED",
    MONITORING_GRAFANA_OKTA_TOKEN: "REDACTED",
    MONITORING_GRAFANA_OKTA_USERINFO: "REDACTED",
    MONITORING_GRAFANA_URL: "REDACTED",
    MONITORING_ALERTMANAGER_URL: "REDACTED",
    MONITORING_PROMETHEUS_URL: "REDACTED",
}